### ISSUE TITLE
RuntimeError: Error code 400 on request when send transaction

### ISSUE THREAD

**Issue by marknguyen85** [INFURA/infura#116]
I'm trying to send transaction
my code here

```
         $web3 = Web3::Eth::Rpc.new host: 'rinkeby.infura.io',
                          port: 443,
                          connect_options: {
                            open_timeout: 20,
                            read_timeout: 140,
                            use_ssl: true,
                            rpc_path: '/' + ENV["INFURA_TOKEN"]
                        }

        key = Eth::Key.new priv: privateKey
        gas_limit = 200000
        gas_price = $web3.eth.gasPrice().to_i(16)
        nonce = $web3.eth.getTransactionCount([key.address, 'pending']).to_i(16)
        tx = Eth::Tx.new({
                gas_limit: 210000,
                gas_price: gas_price,
                nonce: nonce,
                from: key.address,
                to: address_to,
                value: amount,
                data: ""
            })

        tx.sign(key)
        
        result = $web3.eth.sendRawTransaction(tx.hex)
```
then error respose

```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<RuntimeError: Error code 400 on request https://rinkeby.infura.io/kEICAYHkrSFjduGKSOR5 {\"jsonrpc\":\"2.0\",\"method\":\"eth_sendRawTransaction\",\"params\":\"0xf86480843b9aca0083033450945dc73424b8bb75d22cd728dc8dbb2aad77f5fd4680801ba096c8949ec52baa4ef55fdedbc138ed330717a7495ecc70cffd7d4ce05d4cb389a06f3c88b4323cd4f6f0d8bfdb51e788faff621733d48f77622cd598341edb6b15\",\"id\":6401146}>",
    "traces": {
        "Application Trace": [
            {
                "id": 5,
                "trace": "app/walletapi/eth_client.rb:45:in `drawal'"
            },
            {
                "id": 6,
                "trace": "app/controllers/api/v1/wallets_controller.rb:137:in `withdrawal'"
            }
        ],
        "Framework Trace": [
            {
                "id": 0,
                "trace": "web3-eth (0.2.16) lib/web3/eth/rpc.rb:44:in `block in request'"
```

Please help me.

**Comment by ryanschneider** [comment]
Seems like a bug in your web3 library, `params` should be an array, like this:

```json
{
"jsonrpc":"2.0", 
"method":"eth_sendRawTransaction", 
"params":["0xf86480843b9aca0083033450945dc73424b8bb75d22cd728dc8dbb2aad77f5fd4680801ba096c8949ec52baa4ef55fdedbc138ed330717a7495ecc70cffd7d4ce05d4cb389a06f3c88b4323cd4f6f0d8bfdb51e788faff621733d48f77622cd598341edb6b15"], 
"id":6401146
}
```

See: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransaction

If sending a proper JSONRPC the request succeeds fine for me:

```
curl https://rinkeby.infura.io/test -H 'Content-Type: application/json' --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86480843b9aca0083033450945dc73424b8bb75d22cd728dc8dbb2aad77f5fd4680801ba096c8949ec52baa4ef55fdedbc138ed330717a7495ecc70cffd7d4ce05d4cb389a06f3c88b4323cd4f6f0d8bfdb51e788faff621733d48f77622cd598341edb6b15\"],\"id\":6401146}"

{"jsonrpc":"2.0","id":6401146,"result":"0x58fe93c28c799f6e8906f061192e482553ab75a9fc396000456a68b5d45a2fd3"}
```

**Comment by marknguyen85** [comment]
thanks for supported
