### ISSUE TITLE
ipfs.util.addFromFs gets 504 Gateway Time-out from ipfs.infura.io

### ISSUE THREAD

**Issue by TimDaub** [INFURA/infura#145]
```
const ipfs = ipfsAPI('ipfs.infura.io', '5001', {
  protocol: 'https',
});

ipfs.util.addFromFs(
  "myfolder",
  {recursive: true},
  function(err, result) { console.log(err) })
```

Receives a 504 timeout from infura:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

Which looks like this as the returned error value from IPFS:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at streamToValue (/Users/TimDaub/Projects/ipfs-convert/node_modules/ipfs-api/src/utils/stream-to-json-value.js:26:18)
    at concat (/Users/TimDaub/Projects/ipfs-convert/node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
    at ConcatStream.<anonymous> (/Users/TimDaub/Projects/ipfs-convert/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:187:15)
    at finishMaybe (/Users/TimDaub/Projects/ipfs-convert/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/Users/TimDaub/Projects/ipfs-convert/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ramxis** [comment]
I am getting this error as well, were you able to resolve it ?

**Comment by ramxis** [comment]
I think Infura might be filtering this command in their API, as it was working for me about a month ago.

**Comment by ncocchiaro** [comment]
@TimDaub when using addFromFs are you adding content larger than 100M in one call, or getting this timeout after 60 seconds?

**Comment by aliazlan4** [comment]
This error is still present. I am trying to upload a 12MB file using ipfs-http-client nodejs library and it gives 504 gateway timeout error after approximately 75 seconds. Following is the test code to demonstrate this issue:

`
const fs = require('fs');
const IPFS = require('ipfs-http-client');
const ipfs = new IPFS({ host: 'ipfs.infura.io', port: 5001, protocol: 'https' });

let testFile = fs.readFileSync("./2.mp4");
let testBuffer = new Buffer(testFile);

console.log('Starting file upload: ' + testBuffer.length);
const time1 = new Date();

ipfs.add(testBuffer, {progress: progressFun}, function (err, file) {
    const time2 = new Date();

    if (err) {c
        console.log('Error:', err);
    } else
        console.log('File Uploaded: ', file);

    console.log('Time Consumed: ', ((time2 - time1)/1000));
});

function progressFun(progress) {
    console.log('Progress: ' + ((progress * 100) / testBuffer.length));
}
`
