### ISSUE TITLE
getPastEvents does not work anymore

### ISSUE THREAD

**Issue by CineTek** [INFURA/infura#54]
For the last few days and weeks getPastEvents worked like a charm, but starting today we were not able to retrieve any events/logs from infura - has something changed with the way the node works?

**Comment by eccheung4** [comment]
Also have this problem and seeing this error:
```
Error: CONNECTION ERROR: Couldn't connect to node on IPC.
    at Object.InvalidConnection (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-providers-ws/src/index.js:192:48)
    at W3CWebSocket.connection.onclose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/web3-providers-ws/src/index.js:96:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/Users/eccheung4/Documents/Business/metax/adchain-registry-events-db/node_modules/websocket/lib/WebSocketConnection.js:382:14)
    at emitOne (events.js:120:20)
    at TLSSocket.emit (events.js:210:7)
    at _handle.close (net.js:547:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

**Comment by tueric** [comment]
@CineTek @eccheung4 Can you provide more information? Such as the requests you are making

**Comment by CineTek** [comment]
Looks like the problem is that Infura updates Geth which has this bug: https://github.com/ethereum/go-ethereum/issues/15871

**Comment by eccheung4** [comment]
nice find @CineTek thanks!

@tueric I have code that does something like this:

```
  const provider = `wss://rinkeby.infura.io/ws`
  let web3 = new Web3(new Web3.providers.WebsocketProvider(provider))
  let contract = new web3.eth.Contract(contractAbi, contractAddress);

  contract.getPastEvents('allEvents',
    {fromBlock: 0,  toBlock: 'latest'},
    (error, logs) => {
    if (error) console.error(error);
    logs.forEach(log => {
    	// Do something with log
    })
  })
```

**Comment by CineTek** [comment]
Same code except issue on Ropsten using https instead of websockets. Everything worked like a charm and then suddenly stopped working yesterday morning

**Comment by CineTek** [comment]
Looks like geth has been updated by infura, everything working fine for me again 👍

**Comment by StarNeit** [comment]
Anybody here?

**Comment by johanherman** [comment]
Hey @StarNeit. Judging by your later comment in https://github.com/INFURA/infura/issues/29 I take it that you got it resolved?

**Comment by StarNeit** [comment]
Hi @johanherman , it was solved, thank you.

**Comment by jtakalai** [comment]
I'm getting this suddenly today. Could it be related to response size from getPastEvents? Something like that is suggested in #75
