### ISSUE TITLE
Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by vaibhavdesai137** [INFURA/infura#59]
Hey guys. Just created an infura account and trying to deploy a contract. But I keep seeing [Invalid JSON RPC response: ""] error. What am I doing wrong? I have verified the credentials and they are correct. Please help. Thank you.

**Solidity version:** 0.4.19
**Web3 version:** 1.0.0-beta.27

```
const Web3 = require('web3');
const { interface, bytecode } = require('./compile');

const rinkebyAccountAddress = process.env.RINKEBY_ACCOUNT_ADDRESS;
const rinkebyAccountPassword = process.env.RINKEBY_ACCOUNT_PASSWORD;

const infuraKey = process.env.INFURE_KEY;
const infuraRinkebyEndpoint = 'https://rinkeby.infura.io/' + infuraKey;

const web3 = new Web3(infuraRinkebyEndpoint);

// Using this style just to use "async" and "await"
// This is becoz "await" has to be used within a function
const deploy = async() => {

    // WORKS
    console.log('Trying to get balance...');
    const balance = await web3.eth.getBalance(rinkebyAccountAddress);
    console.log('Balance: ' + web3.utils.fromWei(balance, 'ether'));

    try {

        // FAILS
        console.log('\nUnlocking account before contract deploy...')
        const success = await web3.eth.personal.unlockAccount(rinkebyAccountAddress, rinkebyAccountPassword, 500);
        console.log('Account unlocked?: ' + success);

        // FAILS 
        console.log('Attempting rinkeby deploy using account: ' + rinkebyAccountAddress);
        const contract = await new web3.eth.Contract(JSON.parse(interface)).deploy({
            data: bytecode
        }).send({
            from: rinkebyAccountAddress,
            gas: 1000000
        });
        console.log('Contract successfully deployed at: ' + contract.options.address);

    } catch (err) {
        console.log(err);
    }

}

// Trigger the deployment
deploy();
```

Output:

```
Trying to get balance...
Balance: 20.57417915

Unlocking account before contract deploy...
Error: Invalid JSON RPC response: ""

    at Object.InvalidResponse (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/web3-providers-http/src/index.js:60:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/vaidesai/Development/git/vaibhavdesai137/ethereum-stuff/truffle/05-lottery-app/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by harman666666** [comment]
I have the same issue aswell

**Comment by vaibhavdesai137** [comment]
Gotcha. Ended up using truffle-hd-walletprovider and that worked. Thanks.

**Comment by tueric** [comment]
Awesome. Closing issue.

**Comment by albertbanez** [comment]
Hi, can u create an ETH wallet address in Infura?
