### ISSUE TITLE
eth_getLogs randomly returning status code 200 with body equal to "Invalid host specified"

### ISSUE THREAD

**Issue by akhanubis** [INFURA/infura#83]
Hi,

Network: ropsten
The issue first appeared on 2018-02-24T07:31:27.166256+00:00.

I'm running a background worker that makes sendAsync calls with the method eth_getLogs via MetaMask provider engine (using only Filter and Rpc subproviders), and the script keeps crashing randomly when the RpcSubprovider instance tries to parse the response received (body == "Invalid host specified" according to some debug output I added into rpc.js code) as json:

Sample request:
```javascript
{"id":1519504003415476,"jsonrpc":"2.0","params":[{"fromBlock":"0x297b07","toBlock":"0x297b07"}],"method":"eth_getLogs"}
```

Sample error:
```javascript
SyntaxError: Unexpected token i in JSON at position 0
        at JSON.parse (<anonymous>)
        at Request._callback (D:\dev\canvas\node_modules\web3-provider-engine\subproviders\rpc.js:51:19)
        at Request.self.callback (D:\dev\canvas\node_modules\request\request.js:186:22)
        at emitTwo (events.js:126:13)
        at Request.emit (events.js:214:7)
        at Request.<anonymous> (D:\dev\canvas\node_modules\request\request.js:1163:10)
        at emitOne (events.js:116:13)
        at Request.emit (events.js:211:7)
        at IncomingMessage.<anonymous> (D:\dev\canvas\node_modules\request\request.js:1085:12)
        at Object.onceWrapper (events.js:313:30)
```

Infura url: 
    https://ropsten.infura.io/koPGObK3IvOlTaqovf2G

I didn't make any changes to my code around that date so I think this may be related to Infura.

**Comment by ncocchiaro** [comment]
This is an issue we had due to an incorrect deployment. We were able to fully resolve it on mainnet, but as it looks like not yet on the other networks. We're on it.

**Comment by kirillDanshin** [comment]
hi @ncocchiaro @egalano @tueric @johanherman

does anybody got an update on this issue?

**Comment by egalano** [comment]
Apologies for the delay @kirillDanshin. The issue should be resolved. Are you still seeing errors?

**Comment by akhanubis** [comment]
It's fixed for me, thanks!

(Not sure if I should close this or not)

**Comment by egalano** [comment]
Thanks for the ack @akhanubis . I'll close this for now. Please re-open if anyone encounters similar issues
